/**
 * URLs for the landing-page demo: a Polish creator's first English video,
 * dubbed by DubSync into multiple languages with the premium fal.ai
 * `lipsync-2-pro` model.
 *
 * Stored in the public Supabase bucket `landing-assets/polish-girl/`.
 * Generated by `scripts/generate-landing-dubs.ts`.
 *
 * Source video is 720x406 (16:9 landscape). Posters are JPGs of frame 0,
 * uploaded alongside the videos so the player can show a real preview
 * frame without fetching any video bytes.
 */
const BASE =
  "https://jikcnbwjavtbymcvbvfy.supabase.co/storage/v1/object/public/landing-assets/polish-girl";

export type LandingDubLang = {
  code: "original" | "es" | "fr" | "ja";
  label: string;
  flag: string;
  url: string;
  poster: string;
};

export const LANDING_DUB_LANGUAGES: LandingDubLang[] = [
  {
    code: "original",
    label: "Original",
    flag: "🇺🇸",
    url: `${BASE}/original.mp4`,
    poster: `${BASE}/poster-original.jpg`,
  },
  {
    code: "es",
    label: "Spanish",
    flag: "🇪🇸",
    url: `${BASE}/dubbed-es.mp4`,
    poster: `${BASE}/poster-es.jpg`,
  },
  {
    code: "fr",
    label: "French",
    flag: "🇫🇷",
    url: `${BASE}/dubbed-fr.mp4`,
    poster: `${BASE}/poster-fr.jpg`,
  },
  {
    code: "ja",
    label: "Japanese",
    flag: "🇯🇵",
    url: `${BASE}/dubbed-ja.mp4`,
    poster: `${BASE}/poster-ja.jpg`,
  },
];

/** Native pixel dimensions of the source clip (16:9 HD). */
export const LANDING_DUB_VIDEO_WIDTH = 1280;
export const LANDING_DUB_VIDEO_HEIGHT = 720;
